import React from 'react'
import Script from 'next/script'

const Contact = () => {
  return (
    <div>
      <Script strategy="lazyOnload">
       alert("About Contact Page")

      </Script>
      contact
    </div>
  )
}

export default Contact

export const metadata = {
  title: "Contact Next App",
  description: "Generated by create next app",
};
