import React from 'react'

const About = () => {
  return (
    <div>
      About
    </div>
  )
}

export default About

export const metadata = {
    title: "About Next App",
    description: "Generated by create next app",
  };